
clear all
set more off
*Specify directories
global root ""
global dta ""

*******************************************************
*  Property Data - Get SFR and Ag/Vacant then Clean   *
*******************************************************

*************************** Nationwide Bulk Data***************************

*******************************************************
*  Property Data - Get SFR and Ag/Vacant then Clean   *
*******************************************************
*Bulk
*process in chunks
*This takes days

*1
*Add raw assessment data directory and name 
import delimited "E:\\CoreLogic\\...\\..._data.txt", clear bindquotes(nobind) stripquote(no) case(preserve)  rowrange(1:50000000) varnames(1)

drop if MULTIORSPLITPARCELCODE!=""
drop MULTIORSPLITPARCELCODE
drop if PARCELLEVELLATITUDE==. | MAILINGSTREETADDRESS==""
drop TOTALAREASQUAREFOOTAGEOFFICESPAC

drop PREVIOUSPARCELNUMBER PREVIOUSPARCELSEQUENCENUMBER JURISDICTIONCOUNTYCODE TAXDISTRICTMUNICIPALITYNAME WATERDISTRICTNAME TOTALPROPERTYTAXRATEPERCENT TAXABLEOTHERVALUE TOTALNUMBEROFELEVATORSALLBUILDIN TOTALNUMBEROFLOADINGDOCKSALLBUIL TOTALNUMBEROFRAILSPURSALLBUILDIN TOTALNUMBEROFTRUCKDOORSALLBUILDI TOTALNUMBEROF1BEDROOMS TOTALNUMBEROF2BEDROOMS TOTALNUMBEROF3BEDROOMS TOTALNUMBEROFEFFICIENCYUNITS RECORDACTIONINDICATOR

*Nobs 24.36 m

gen SFR = 1 if LANDUSECODE==112 | LANDUSECODE==163
replace SFR =0 if SFR==.
gen Ag = 1 if LANDUSECODE==430 | (LANDUSECODE>=500 & LANDUSECODE<600) | LANDUSECODE==400 | LANDUSECODE== 481
replace Ag = 0 if Ag==.

keep if SFR==1 | Ag==1
*Nobs  m

sort SITUSSTATE SITUSCOUNTY SITUSCITY SITUSZIPCODE MAILINGSTREETADDRESS 
tab ASSESSEDYEAR
* Only current assessment data here

drop CLIP APNSEQUENCENUMBER TAXACCOUNTNUMBER ALTERNATEPARCELID PREVIOUSPARCELNUMBERFORMATTED VIEWCODE LOCATIONINFLUENCECODE OWNER2FULLNAME-OWNER4CORPORATEINDICATOR SALERECORDEDDOCUMENTNUMBER-SELLERNAME
save "$dta\CoreLogic_CurAss_SFR_AG_Bulk_1.dta",replace

*2 
clear all
*Add raw assessment data directory and name 
import delimited "E:\\CoreLogic\\...\\..._data.txt", clear bindquotes(nobind) stripquote(no) case(preserve) rowrange(50000001:100000000) varnames(1)

drop if MULTIORSPLITPARCELCODE!=""
drop MULTIORSPLITPARCELCODE
drop if PARCELLEVELLATITUDE==. | MAILINGSTREETADDRESS==""
drop TOTALAREASQUAREFOOTAGEOFFICESPAC

drop PREVIOUSPARCELNUMBER PREVIOUSPARCELSEQUENCENUMBER JURISDICTIONCOUNTYCODE TAXDISTRICTMUNICIPALITYNAME WATERDISTRICTNAME TOTALPROPERTYTAXRATEPERCENT TAXABLEOTHERVALUE TOTALNUMBEROFELEVATORSALLBUILDIN TOTALNUMBEROFLOADINGDOCKSALLBUIL TOTALNUMBEROFRAILSPURSALLBUILDIN TOTALNUMBEROFTRUCKDOORSALLBUILDI TOTALNUMBEROF1BEDROOMS TOTALNUMBEROF2BEDROOMS TOTALNUMBEROF3BEDROOMS TOTALNUMBEROFEFFICIENCYUNITS RECORDACTIONINDICATOR

gen SFR = 1 if LANDUSECODE==112 | LANDUSECODE==163
replace SFR =0 if SFR==.
gen Ag = 1 if LANDUSECODE==430 | (LANDUSECODE>=500 & LANDUSECODE<600) | LANDUSECODE==400 | LANDUSECODE== 481
replace Ag = 0 if Ag==.

keep if SFR==1 | Ag==1
*Nobs  m

sort SITUSSTATE SITUSCOUNTY SITUSCITY SITUSZIPCODE MAILINGSTREETADDRESS 
tab ASSESSEDYEAR
* Only current assessment data here
drop CLIP APNSEQUENCENUMBER TAXACCOUNTNUMBER ALTERNATEPARCELID PREVIOUSPARCELNUMBERFORMATTED VIEWCODE LOCATIONINFLUENCECODE OWNER2FULLNAME-OWNER4CORPORATEINDICATOR SALERECORDEDDOCUMENTNUMBER-SELLERNAME
save "$dta\CoreLogic_CurAss_SFR_AG_Bulk_2.dta",replace


*3
clear all
*Add raw assessment data directory and name 
import delimited "E:\\CoreLogic\\...\\..._data.txt", clear bindquotes(nobind) stripquote(no) case(preserve) rowrange(100000001:150000000) varnames(1)

drop if MULTIORSPLITPARCELCODE!=""
drop MULTIORSPLITPARCELCODE
drop if PARCELLEVELLATITUDE==. | MAILINGSTREETADDRESS==""
drop TOTALAREASQUAREFOOTAGEOFFICESPAC

drop PREVIOUSPARCELNUMBER PREVIOUSPARCELSEQUENCENUMBER JURISDICTIONCOUNTYCODE TAXDISTRICTMUNICIPALITYNAME WATERDISTRICTNAME TOTALPROPERTYTAXRATEPERCENT TAXABLEOTHERVALUE TOTALNUMBEROFELEVATORSALLBUILDIN TOTALNUMBEROFLOADINGDOCKSALLBUIL TOTALNUMBEROFRAILSPURSALLBUILDIN TOTALNUMBEROFTRUCKDOORSALLBUILDI TOTALNUMBEROF1BEDROOMS TOTALNUMBEROF2BEDROOMS TOTALNUMBEROF3BEDROOMS TOTALNUMBEROFEFFICIENCYUNITS RECORDACTIONINDICATOR

gen SFR = 1 if LANDUSECODE==112 | LANDUSECODE==163
replace SFR =0 if SFR==.
gen Ag = 1 if LANDUSECODE==430 | (LANDUSECODE>=500 & LANDUSECODE<600) | LANDUSECODE==400 | LANDUSECODE== 481
replace Ag = 0 if Ag==.

keep if SFR==1 | Ag==1
*Nobs  m

sort SITUSSTATE SITUSCOUNTY SITUSCITY SITUSZIPCODE MAILINGSTREETADDRESS 
tab ASSESSEDYEAR
* Only current assessment data here
drop CLIP APNSEQUENCENUMBER TAXACCOUNTNUMBER ALTERNATEPARCELID PREVIOUSPARCELNUMBERFORMATTED VIEWCODE LOCATIONINFLUENCECODE OWNER2FULLNAME-OWNER4CORPORATEINDICATOR SALERECORDEDDOCUMENTNUMBER-SELLERNAME
save "$dta\CoreLogic_CurAss_SFR_AG_Bulk_3.dta",replace


*4
clear all
*Add raw assessment data directory and name 
import delimited "E:\\CoreLogic\\...\\..._data.txt", clear bindquotes(nobind) stripquote(no) case(preserve) rowrange(150000001:200000000) varnames(1)

drop if MULTIORSPLITPARCELCODE!=""
drop MULTIORSPLITPARCELCODE
drop if PARCELLEVELLATITUDE==. | MAILINGSTREETADDRESS==""
drop TOTALAREASQUAREFOOTAGEOFFICESPAC

drop PREVIOUSPARCELNUMBER PREVIOUSPARCELSEQUENCENUMBER JURISDICTIONCOUNTYCODE TAXDISTRICTMUNICIPALITYNAME WATERDISTRICTNAME TOTALPROPERTYTAXRATEPERCENT TAXABLEOTHERVALUE TOTALNUMBEROFELEVATORSALLBUILDIN TOTALNUMBEROFLOADINGDOCKSALLBUIL TOTALNUMBEROFRAILSPURSALLBUILDIN TOTALNUMBEROFTRUCKDOORSALLBUILDI TOTALNUMBEROF1BEDROOMS TOTALNUMBEROF2BEDROOMS TOTALNUMBEROF3BEDROOMS TOTALNUMBEROFEFFICIENCYUNITS RECORDACTIONINDICATOR

gen SFR = 1 if LANDUSECODE==112 | LANDUSECODE==163
replace SFR =0 if SFR==.
gen Ag = 1 if LANDUSECODE==430 | (LANDUSECODE>=500 & LANDUSECODE<600) | LANDUSECODE==400 | LANDUSECODE== 481
replace Ag = 0 if Ag==.

keep if SFR==1 | Ag==1
*Nobs  m
sort SITUSSTATE SITUSCOUNTY SITUSCITY SITUSZIPCODE MAILINGSTREETADDRESS 
tab ASSESSEDYEAR
* Only current assessment data here
drop CLIP APNSEQUENCENUMBER TAXACCOUNTNUMBER ALTERNATEPARCELID PREVIOUSPARCELNUMBERFORMATTED VIEWCODE LOCATIONINFLUENCECODE OWNER2FULLNAME-OWNER4CORPORATEINDICATOR SALERECORDEDDOCUMENTNUMBER-SELLERNAME
save "$dta\CoreLogic_CurAss_SFR_AG_Bulk_4.dta",replace

*For each chunk, about a little more than one half left after a few steps of purging unrelated (including purging states already processed) 

use "$dta\CoreLogic_CurAss_SFR_AG_Bulk_1.dta",clear
append using "$dta\CoreLogic_CurAss_SFR_AG_Bulk_2.dta"
append using "$dta\CoreLogic_CurAss_SFR_AG_Bulk_3.dta"
append using "$dta\CoreLogic_CurAss_SFR_AG_Bulk_4.dta"
save "$dta\CoreLogic_CurAss_SFR_AG_Bulk.dta",replace

******************************************************
*    Transaction - Clean and Merge with Property     *
******************************************************
*Raw data Process - process in chunks - 487275248 records
*This takes days
foreach n of numlist 1(1) 10{
	clear all
	di `n'
	local lb = (`n'-1)*50000000 + 1 
	local ub = (`n')*50000000
    *Add raw transaction data directory and name 
	import delimited "E:\\CoreLogic\\...\\..._data.txt", clear bindquotes(nobind) stripquote(no) case(preserve) rowrange(`lb':`ub') varnames(1)
	drop if SHORTSALEINDICATOR==1
	drop if FORECLOSUREREOINDICATOR==1
	drop if FORECLOSUREREOSALEINDICATOR==1
	drop if NEWCONSTRUCTIONINDICATOR==1
	drop if INVESTORPURCHASEINDICATOR==1 
	drop if INTERFAMILYRELATEDINDICATOR==1
	tab CASHPURCHASEINDICATOR
	*Cash based arm's length transaction 

	drop if PENDINGRECORDINDICATOR=="Y"
	*Could not be matched with tax roll 

	drop if STANDARDIZEDADDRESSCONFIDENCECOD==""
	*Unverifiable address 

	save "$dta\CoreLogic_Trans_Bulk1_`n'.dta",replace
}

*Merge
foreach n of numlist 1(1) 10{
	
	clear all
	use "$dta\CoreLogic_Trans_Bulk1_`n'.dta",clear
	merge m:1 COMPOSITEPROPERTYLINKAGEKEY using"$dta\CoreLogic_CurAss_SFR_AG_Bulk1_1.dta"
	drop if _merge==2
	gen ass_found = (_merge==3)
	drop _merge

	merge m:1 COMPOSITEPROPERTYLINKAGEKEY using"$dta\CoreLogic_CurAss_SFR_AG_Bulk1_2.dta", update
	drop if _merge==2
	replace ass_found=1 if _merge==3 | _merge==4 | _merge==5
	drop _merge
	
	merge m:1 COMPOSITEPROPERTYLINKAGEKEY using"$dta\CoreLogic_CurAss_SFR_AG_Bulk1_3.dta", update
	drop if _merge==2
	replace ass_found=1 if _merge==3 | _merge==4 | _merge==5
	drop _merge
	
	merge m:1 COMPOSITEPROPERTYLINKAGEKEY using"$dta\CoreLogic_CurAss_SFR_AG_Bulk1_4.dta", update
	drop if _merge==2
	replace ass_found=1 if _merge==3 | _merge==4 | _merge==5
	drop _merge
	
	tab ass_found
	drop if ass_found==0
	* sales not matched due to not being SFR or not Ag or not in the five states
	* properties not matched due to having no sales in record
	* mi sales matched

	/*Check all building squarefootage variable
	foreach v in TOTALLIVINGAREASQUAREFEETALLBUIL UNIVERSALBUILDINGSQUAREFEET  {
		di "`v'"
		count if `v'==.
		
	}
	*/
	drop BASEMENTAREASQUAREFEET BUILDINGADJUSTEDAREASQUAREFEET BUILDINGAREASQUAREFEET BUILDINGGROSSAREASQUAREFEET FINISHEDBASEMENTAREASQUAREFEET GARAGEORPARKINGSQUAREFEET GROUNDFLOORAREASQUAREFEET SECONDFLOORAREASQUAREFEET TOTALAREASQUAREFOOTAGEALLBUILDIN TOTALLANDSQUAREFOOTAGE TOTALSQUAREFOOTAGEOPENAREAS UNFINISHEDBASEMENTAREASQUAREFEET UNIVERSALBUILDINGSQUAREFEET UNIVERSALBUILDINGSQUAREFEETSOURC

	ren TOTALLIVINGAREASQUAREFEETALLBUIL LivingSQFT
	drop if LivingSQFT==. & NoofBuildings!=.
	*99 percentile: 4997 sqft
	drop if LivingSQFT>=10000
	
	/*Check all bath room number variable
	foreach v in TOTALNUMBEROF1QTRBATHSALLBUILDIN TOTALNUMBEROF3QTRBATHSALLBUILDIN TOTALNUMBEROFBATHFIXTURES TOTALNUMBEROFBATHFIXTURESALLBUIL TOTALNUMBEROFBATHROOMS TOTALNUMBEROFFULLBATHSALLBUILDIN TOTALNUMBEROFHALFBATHSALLBUILDIN TOTALNUMBEROFBATHROOMSALLBUILDIN {
			di "`v'"
		count if `v'==.
	}
	*/
	drop TOTALNUMBEROF1QTRBATHSALLBUILDIN TOTALNUMBEROF3QTRBATHSALLBUILDIN TOTALNUMBEROFBATHFIXTURES TOTALNUMBEROFBATHFIXTURESALLBUIL TOTALNUMBEROFBATHROOMS TOTALNUMBEROFFULLBATHSALLBUILDIN TOTALNUMBEROFHALFBATHSALLBUILDIN
	ren TOTALNUMBEROFBATHROOMSALLBUILDIN TotalBathroomNum
	
	/*Room number variable
	foreach v in TOTALNUMBEROFBEDROOMSALLBUILDING TOTALNUMBEROFROOMSALLBUILDINGS {
		di "`v'"
		count if `v'==.
	}
	*/
	ren TOTALNUMBEROFBEDROOMSALLBUILDING TotalBedroomNum
	ren TOTALNUMBEROFROOMSALLBUILDINGS TotalRoomNum
	*Fireplace number variable
	ren TOTALNUMBEROFFIREPLACES NoofFirePlace
	drop FIREPLACEINDICATOR FIREPLACETYPECODE
	*Building number variable
	ren TOTALNUMBEROFBUILDINGS NoofBuildings
	ren TOTALNUMBEROFSTORIES NoofStories
	ren TOTALNUMBEROFUNITSALLBUILDINGS NoofUnits

	*Categorical Indicators
	drop BASEMENTFINISHTYPECODE BASEMENTTYPECODE FLOORTYPECODE STORIESTYPECODE FRAMETYPECODE ROOFCOVERTYPECODE UTILITIESTYPECODE BUILDINGFUELTYPECODE

	global CATE "AIRCONDITIONINGTYPECODE HEATINGTYPECODE BUILDINGTYPECODE BUILDINGIMPROVEMENTCONDITIONCODE CONSTRUCTIONTYPECODE EXTERIORWALLTYPECODE FOUNDATIONTYPECODE GARAGETYPECODE TOTALNUMBEROFPARKINGSPACES PARKINGTYPECODE POOLINDICATOR POOLTYPECODE BUILDINGQUALITYCODE ROOFTYPECODE BUILDINGSTYLETYPECODE  FUELTYPECODE ELECTRICITYWIRINGTYPECODE SEWERTYPECODE UTILITIESTYPECODE WATERTYPECODE"

	global X "LivingSQFT TotalBathroomNum TotalBedroomNum TotalRoomNum NoofFirePlace NoofBuildings NoofStories NoofUnits"
	*Dealing with missing values later by state

	gen SALE_Year = floor(SALEDERIVEDDATE/10000)
	save "$dta\CoreLogic_Merged_SFR_AG_Bulk_`n'.dta",replace

}


************************************
*  Aggregate Assessment Data Only  *
************************************
/*
use "$dta\CoreLogic_CurAss_SFR_AG_Bulk_1.dta",clear
append using "$dta\CoreLogic_CurAss_SFR_AG_Bulk_2.dta"
append using "$dta\CoreLogic_CurAss_SFR_AG_Bulk_3.dta"
append using "$dta\CoreLogic_CurAss_SFR_AG_Bulk_4.dta"
compress

save "$dta\CoreLogic_CurAss_All.dta",replace

use "$dta\CoreLogic_CurAss_All.dta",clear
keep if Ag==1
save "$dta\CoreLogic_CurAss_Ag.dta",replace

use "$dta\CoreLogic_CurAss_All.dta",clear
keep if SFR==1 
save "$dta\CoreLogic_CurAss_SFR.dta",replace
*/

